#pragma once
enum class BRIDGE_TEXTURE_ID
{
	BRIDGE_BODY_00,
	BRIDGE_BODY_01,
	BRIDGE_BODY_02,

	BRIDGE_EXPLOSION_00,
	BRIDGE_EXPLOSION_01,
	BRIDGE_EXPLOSION_02,
	BRIDGE_EXPLOSION_03,
	BRIDGE_EXPLOSION_04,
	BRIDGE_EXPLOSION_05,
	BRIDGE_EXPLOSION_06,
	BRIDGE_EXPLOSION_07,
	BRIDGE_EXPLOSION_08,
	BRIDGE_EXPLOSION_09,
	BRIDGE_EXPLOSION_10,
	BRIDGE_EXPLOSION_11,
	BRIDGE_EXPLOSION_12,
	BRIDGE_EXPLOSION_13,
	BRIDGE_EXPLOSION_14,

	BRIDGE_HEAD_00,
	BRIDGE_HEAD_01,
	BRIDGE_HEAD_02,

	BRIDGE_TAIL_00,
	BRIDGE_TAIL_01,
	BRIDGE_TAIL_02,
};

enum class BRIDGE_SPRITE_ID
{
	BRIDGE_BODY_00,
	BRIDGE_BODY_01,
	BRIDGE_BODY_02,

	BRIDGE_EXPLOSION_00,
	BRIDGE_EXPLOSION_01,
	BRIDGE_EXPLOSION_02,
	BRIDGE_EXPLOSION_03,
	BRIDGE_EXPLOSION_04,
	BRIDGE_EXPLOSION_05,
	BRIDGE_EXPLOSION_06,
	BRIDGE_EXPLOSION_07,
	BRIDGE_EXPLOSION_08,
	BRIDGE_EXPLOSION_09,
	BRIDGE_EXPLOSION_10,
	BRIDGE_EXPLOSION_11,
	BRIDGE_EXPLOSION_12,
	BRIDGE_EXPLOSION_13,
	BRIDGE_EXPLOSION_14,

	BRIDGE_HEAD_00,
	BRIDGE_HEAD_01,
	BRIDGE_HEAD_02,

	BRIDGE_TAIL_00,
	BRIDGE_TAIL_01,
	BRIDGE_TAIL_02,
};

enum class BRIDGE_ANIMATION_ID
{
	HEAD,
	TAIL,
	BODY,
	EXPLOSION
};